# # 없어진 기록 찾기
# SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
# FROM ANIMAL_INS RIGHT OUTER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
# WHERE ANIMAL_INS.ANIMAL_ID IS NULL
#
# # 있었는데요 없었습니다
# SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
# FROM ANIMAL_INS INNER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
# WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
# ORDER BY ANIMAL_INS.DATETIME
#
# # 오랜 기간 보호한 동물
# SELECT ANIMAL_INS.NAME AS NAME, ANIMAL_INS.DATETIME AS DATETIME
# FROM ANIMAL_INS LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
# WHERE ANIMAL_OUTS.ANIMAL_ID IS NULL
# ORDER BY ANIMAL_INS.DATETIME
# LIMIT 3
#
# # 보호소에서 중성화한 동물
# SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
# FROM ANIMAL_INS LEFT OUTER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
# WHERE ANIMAL_INS.SEX_UPON_INTAKE != ANIMAL_OUTS.SEX_UPON_OUTCOME
# ORDER BY ANIMAL_INS.ANIMAL_ID